export const mockPartners = [
    {
      id: '1',
      name: 'Alex Johnson',
      profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      bio: 'Passionate marathon runner with 5 years of experience. Looking for training partners for upcoming city marathon events.',
      location: 'Boston, USA',
      eventTypes: ['Marathon', 'Half Marathon', '10K'],
      experienceLevel: 'Advanced',
      fitnessGoals: ['Improve Endurance', 'Speed Training', 'Weight Management'],
      preferences: ['Outdoor Training', 'Group Sessions', 'Morning Runs'],
      trainingSchedule: {
        monday: { morning: true, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        wednesday: { morning: true, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        thursday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '18:00' },
        friday: { morning: true, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: true, morningTime: '07:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 42.3601, lng: -71.0589 }
    },
    {
      id: '2',
      name: 'Sarah Williams',
      profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      bio: 'OCR enthusiast and CrossFit coach. I train 6 days a week and looking for motivated partners for Spartan races.',
      location: 'Denver, USA',
      eventTypes: ['OCR', 'CrossFit Competition', '5K'],
      experienceLevel: 'Elite',
      fitnessGoals: ['Strength Training', 'Obstacle Technique', 'Muscle Gain'],
      preferences: ['Outdoor Training', 'One-on-One', 'Group Sessions'],
      trainingSchedule: {
        monday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '15:00', evening: true, eveningTime: '19:00' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '15:00', evening: true, eveningTime: '19:00' },
        wednesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        thursday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '15:00', evening: true, eveningTime: '19:00' },
        friday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '15:00', evening: true, eveningTime: '19:00' },
        saturday: { morning: true, morningTime: '08:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: true, morningTime: '08:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 39.7392, lng: -104.9903 }
    },
    {
      id: '3',
      name: 'Michael Chen',
      profileImage: 'https://randomuser.me/api/portraits/men/67.jpg',
      bio: 'Triathlete preparing for Ironman. Looking for swimming, cycling, and running partners who are serious about training consistently.',
      location: 'San Diego, USA',
      eventTypes: ['Triathlon', 'Marathon', 'Swimming'],
      experienceLevel: 'Intermediate',
      fitnessGoals: ['Endurance', 'Technique Improvement', 'Race Preparation'],
      preferences: ['Group Sessions', 'Virtual Training', 'Early Mornings'],
      trainingSchedule: {
        monday: { morning: true, morningTime: '05:30', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        tuesday: { morning: true, morningTime: '05:30', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        wednesday: { morning: true, morningTime: '05:30', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '18:00' },
        thursday: { morning: true, morningTime: '05:30', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        friday: { morning: true, morningTime: '05:30', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '14:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '14:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 32.7157, lng: -117.1611 }
    },
    {
      id: '4',
      name: 'Emma Taylor',
      profileImage: 'https://randomuser.me/api/portraits/women/33.jpg',
      bio: 'Beginner runner looking to improve 5K time. Would love to find patient running partners who can help me with technique and pacing.',
      location: 'Chicago, USA',
      eventTypes: ['5K', '10K'],
      experienceLevel: 'Beginner',
      fitnessGoals: ['Improve Endurance', 'Weight Loss', 'Technique Learning'],
      preferences: ['Outdoor Training', 'Group Sessions', 'Weekends'],
      trainingSchedule: {
        monday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '18:30' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        wednesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '18:30' },
        thursday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        friday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: true, morningTime: '09:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: true, morningTime: '09:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 41.8781, lng: -87.6298 }
    },
    {
      id: '5',
      name: 'David Rodriguez',
      profileImage: 'https://randomuser.me/api/portraits/men/91.jpg',
      bio: 'CrossFit enthusiast with 3 years of experience. Looking for a partner to push each other in workouts and prepare for local competitions.',
      location: 'Miami, USA',
      eventTypes: ['CrossFit Competition', 'OCR'],
      experienceLevel: 'Advanced',
      fitnessGoals: ['Strength', 'Power', 'Competition Preparation'],
      preferences: ['Indoor Training', 'One-on-One', 'Afternoon Sessions'],
      trainingSchedule: {
        monday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '16:00', evening: false, eveningTime: '18:00' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '16:00', evening: false, eveningTime: '18:00' },
        wednesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        thursday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '16:00', evening: false, eveningTime: '18:00' },
        friday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '16:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '14:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 25.7617, lng: -80.1918 }
    },
    {
      id: '6',
      name: 'Olivia Bennett',
      profileImage: 'https://randomuser.me/api/portraits/women/17.jpg',
      bio: 'Yoga instructor and trail runner. Looking for mindful training partners for upcoming half marathons and trail races.',
      location: 'Portland, USA',
      eventTypes: ['Half Marathon', 'Trail Running', '10K'],
      experienceLevel: 'Intermediate',
      fitnessGoals: ['Endurance', 'Mindfulness', 'Balance'],
      preferences: ['Outdoor Training', 'Group Sessions', 'Morning Runs'],
      trainingSchedule: {
        monday: { morning: true, morningTime: '07:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '17:30' },
        wednesday: { morning: true, morningTime: '07:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        thursday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '17:30' },
        friday: { morning: true, morningTime: '07:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: true, morningTime: '08:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 45.5051, lng: -122.6750 }
    },
    {
      id: '7',
      name: 'James Wilson',
      profileImage: 'https://randomuser.me/api/portraits/men/4.jpg',
      bio: 'Former college athlete transitioning to OCR. Strong and looking to improve running endurance for upcoming Tough Mudder.',
      location: 'Austin, USA',
      eventTypes: ['OCR', '5K', 'Half Marathon'],
      experienceLevel: 'Intermediate',
      fitnessGoals: ['Obstacle Technique', 'Running Endurance', 'Upper Body Strength'],
      preferences: ['Outdoor Training', 'Group Sessions', 'Weekend Warriors'],
      trainingSchedule: {
        monday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '19:00' },
        tuesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '19:00' },
        wednesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        thursday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '19:00' },
        friday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: true, morningTime: '09:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: true, morningTime: '09:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 30.2672, lng: -97.7431 }
    },
    {
      id: '8',
      name: 'Sophia Garcia',
      profileImage: 'https://randomuser.me/api/portraits/women/63.jpg',
      bio: 'Elite marathoner with 10+ races under my belt. Looking for serious training partners for Boston qualification.',
      location: 'New York, USA',
      eventTypes: ['Marathon', 'Half Marathon', '10K'],
      experienceLevel: 'Elite',
      fitnessGoals: ['Marathon PR', 'Boston Qualification', 'Pacing Strategy'],
      preferences: ['Outdoor Training', 'One-on-One', 'Early Mornings'],
      trainingSchedule: {
        monday: { morning: true, morningTime: '05:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        tuesday: { morning: true, morningTime: '05:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        wednesday: { morning: false, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: true, eveningTime: '18:00' },
        thursday: { morning: true, morningTime: '05:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        friday: { morning: true, morningTime: '05:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        saturday: { morning: true, morningTime: '06:00', afternoon: false, afternoonTime: '12:00', evening: false, eveningTime: '18:00' },
        sunday: { morning: false, morningTime: '06:00', afternoon: true, afternoonTime: '13:00', evening: false, eveningTime: '18:00' },
      },
      available: true,
      coordinates: { lat: 40.7128, lng: -74.0060 }
    }
  ];
  